Tensor Operations:


From links:
https://www.tensorflow.org/tutorials/quickstart/advanced (Links to an external site.)

 (Links to an external site.)https://www.tensorflow.org/tutorials/keras/regression (Links to an external site.)

 (Links to an external site.)https://www.tensorflow.org/tutorials/keras/classification (Links to an external site.) (Links to an external site.)

https://www.tensorflow.org/tutorials/keras/text_classification_with_hub (Links to an external site.)

 (Links to an external site.)

https://www.tensorflow.org/tutorials/keras/overfit_and_underfit (Links to an external site.) (Links to an external site.)

https://www.tensorflow.org/tutorials/keras/save_and_load (Links to an external site.) (Links to an external site.)

https://www.tensorflow.org/tutorials/load_data/tfrecord (Links to an external site.) (Links to an external site.)

 (Links to an external site.)

Basics of tensors ; https://www.tensorflow.org/tutorials/customization/basics

In [0]:
import tensorflow as tf

In [13]:
print(tf.add(1, 2))

tf.Tensor(3, shape=(), dtype=int32)


In [15]:
print(tf.add([1, 100], [3, 4]))

tf.Tensor([  4 104], shape=(2,), dtype=int32)


In [16]:
print(tf.square(5))
print(tf.reduce_sum([10, 2, 3]))

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


In [17]:
print(tf.square(2) + tf.square(10))

tf.Tensor(104, shape=(), dtype=int32)


In [18]:
x = tf.matmul([[1]], [[2, 30]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[ 2 30]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [19]:
import numpy as np

ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [20]:
print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [21]:
print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [22]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.config.experimental.list_physical_devices("GPU"))

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Is the Tensor on GPU #0:  
True


In [23]:
import time

def time_matmul(x):
  start = time.time()
  for loop in range(10):
    tf.matmul(x, x)

  result = time.time()-start

  print("10 loops: {:0.2f}ms".format(1000*result))

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random.uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

# Force execution on GPU #0 if available
if tf.config.experimental.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
10 loops: 263.33ms
On GPU:
10 loops: 0.40ms


In [0]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [0]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [26]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)

print('\nElements in ds_file:')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([16  4], shape=(2,), dtype=int32)
tf.Tensor([36 25], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)
